services:

    #
    # Controllers with command bus
    #
    apisearch_server.controller_with_command_bus:
        class: Apisearch\Server\Controller\ControllerWithBus
        abstract: true
        arguments:
            - "@apisearch_server.command_bus"

    apisearch_server.create_index_controller:
        class: Apisearch\Server\Controller\CreateIndexController
        parent: apisearch_server.controller_with_command_bus

    apisearch_server.delete_index_controller:
        class: Apisearch\Server\Controller\DeleteIndexController
        parent: apisearch_server.controller_with_command_bus

    apisearch_server.reset_index_controller:
        class: Apisearch\Server\Controller\ResetIndexController
        parent: apisearch_server.controller_with_command_bus

    apisearch_server.add_token_controller:
        class: Apisearch\Server\Controller\AddTokenController
        parent: apisearch_server.controller_with_command_bus

    apisearch_server.delete_token_controller:
        class: Apisearch\Server\Controller\DeleteTokenController
        parent: apisearch_server.controller_with_command_bus

    apisearch_server.delete_tokens_controller:
        class: Apisearch\Server\Controller\DeleteTokensController
        parent: apisearch_server.controller_with_command_bus

    apisearch_server.add_interaction_controller:
        class: Apisearch\Server\Controller\AddInteractionController
        parent: apisearch_server.controller_with_command_bus

    apisearch_server.delete_all_interactions_controller:
        class: Apisearch\Server\Controller\DeleteAllInteractionsController
        parent: apisearch_server.controller_with_command_bus

    apisearch_server.index_items_controller:
        class: Apisearch\Server\Controller\IndexItemsController
        parent: apisearch_server.controller_with_command_bus

    apisearch_server.update_items_controller:
        class: Apisearch\Server\Controller\UpdateItemsController
        parent: apisearch_server.controller_with_command_bus

    apisearch_server.delete_items_controller:
        class: Apisearch\Server\Controller\DeleteItemsController
        parent: apisearch_server.controller_with_command_bus

    #
    # Controllers with query bus
    #
    apisearch_server.controller_with_query_bus:
        class: Apisearch\Server\Controller\ControllerWithBus
        abstract: true
        arguments:
            - "@apisearch_server.query_bus"

    apisearch_server.query_controller:
        class: Apisearch\Server\Controller\QueryController
        parent: apisearch_server.controller_with_query_bus

    apisearch_server.events_controller:
        class: Apisearch\Server\Controller\EventsController
        parent: apisearch_server.controller_with_query_bus

    apisearch_server.logs_controller:
        class: Apisearch\Server\Controller\LogsController
        parent: apisearch_server.controller_with_query_bus

    apisearch_server.configure_index_controller:
        class: Apisearch\Server\Controller\ConfigureIndexController
        parent: apisearch_server.controller_with_query_bus

    apisearch_server.check_health_controller:
        class: Apisearch\Server\Controller\CheckHealthController
        parent: apisearch_server.controller_with_query_bus

    apisearch_server.ping_controller:
        class: Apisearch\Server\Controller\PingController
        parent: apisearch_server.controller_with_query_bus

    apisearch_server.check_index_controller:
        class: Apisearch\Server\Controller\CheckIndexController
        parent: apisearch_server.controller_with_query_bus

    apisearch_server.get_tokens_controller:
        class: Apisearch\Server\Controller\GetTokensController
        parent: apisearch_server.controller_with_query_bus


    apisearch_server.get_indices_controller:
        class: Apisearch\Server\Controller\GetIndicesController
        parent: apisearch_server.controller_with_query_bus


    #
    # Controller listener
    #
    apisearch_server.php_exception_to_json_response_listener:
        class: Apisearch\Server\Controller\Listener\PHPExceptionToJsonResponse
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    apisearch_server.content_type_validation_over_http:
        class: Apisearch\Server\Controller\Listener\ContentTypeValidationOverHTTP
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: validateContentTypeOnKernelRequest }

    apisearch_server.token_validation_over_http:
        class: Apisearch\Server\Controller\Listener\TokenValidationOverHTTP
        arguments:
            - "@apisearch_server.token_validator"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: validateTokenOnKernelRequest }

    apisearch_server.token_cache_over_http:
        class: Apisearch\Server\Controller\Listener\TokenCacheOverHTTP
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: addCacheControlOnKernelResponse }
